language: node_js

node_js:
  - "6"

services:
  - docker
  - xvfb

git:
  depth: 30

dist: xenial
sudo: true

addons:
  jwt:
     secure: YlCp9qGHmnnATcScIQVyOt8eI9FxLhMGAz9iRTHh7r41ADjfGJUzyqkWoBLcCagiQWtqtUujukPAtRuOibbBp9SvmGp+IIdbwHVUDvSZNOvGxkQ1qczeGxJcnht+2YNoCwfzkHW4vFrNiGOULdjvbWAB4sAJ8N0AZPShURwXU1E=

before_install:
  # Because Saucelabs doesnt proxy 5984 on OSX
  - "if [ -z \"$COUCH_HOST\" ]; then export COUCH_HOST=http://127.0.0.1:3000; fi"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Fail early so we dont run hours of saucelabs if we know there
  # is a lint failure
  - npm run eslint

# travis_retry will try up to 3 times to run the script. our tests
# are flaky enough (Selenium, SauceLabs, network, etc.) that this
# mitigates a lot of false negatives
script: travis_retry npm run $COMMAND

env:
  global:
  - NPM_CONFIG_PROGRESS="false"
  - SAUCE_USERNAME=pouchdb

  matrix:
  - CLIENT=selenium:firefox COMMAND=test TRY=1
  - CLIENT=selenium:firefox COMMAND=test TRY=2
