language: node_js

node_js:
  - "6"

services:
  - docker

git:
  depth: 30

dist: xenial
sudo: true

addons:
  firefox: latest-est
  jwt:
     secure: YlCp9qGHmnnATcScIQVyOt8eI9FxLhMGAz9iRTHh7r41ADjfGJUzyqkWoBLcCagiQWtqtUujukPAtRuOibbBp9SvmGp+IIdbwHVUDvSZNOvGxkQ1qczeGxJcnht+2YNoCwfzkHW4vFrNiGOULdjvbWAB4sAJ8N0AZPShURwXU1E=

before_install:
  # Because Saucelabs doesnt proxy 5984 on OSX
  - "if [ -z \"$COUCH_HOST\" ]; then export COUCH_HOST=http://127.0.0.1:3000; fi"

before_script:
  # Fail early so we dont run hours of saucelabs if we know there
  # is a lint failure
  - npm run eslint

# travis_retry will try up to 3 times to run the script. our tests
# are flaky enough (Selenium, SauceLabs, network, etc.) that this
# mitigates a lot of false negatives
script: travis_retry npm run $COMMAND

env:
  global:
  - NPM_CONFIG_PROGRESS="false"
  - SAUCE_USERNAME=pouchdb

  matrix:
  - PERF=1 COMMAND=test TRY=1
  - PERF=1 COMMAND=test TRY=2
  - PERF=1 COMMAND=test TRY=3
  - PERF=1 COMMAND=test TRY=4
  - PERF=1 COMMAND=test TRY=5

matrix:
  fast_finish: true
  include:
    - node_js: "8"
      services: docker
      env: CLIENT=node COMMAND=test
    - node_js: "10"
      services: docker
      env: CLIENT=node COMMAND=test
  allow_failures:
    - env: GREP=suite2 SKIP_MIGRATION=true CLIENT="saucelabs:MicrosoftEdge:14:Windows 10" COMMAND=test
    - env: GREP=suite2 INVERT=true SKIP_MIGRATION=true CLIENT="saucelabs:MicrosoftEdge:14:Windows 10" COMMAND=test
    - env: GREP=suite2 SKIP_MIGRATION=true CLIENT="saucelabs:internet explorer:11:Windows 10" COMMAND=test
    - env: GREP=suite2 INVERT=true SKIP_MIGRATION=true CLIENT="saucelabs:internet explorer:11:Windows 10" COMMAND=test
    - env: SKIP_MIGRATION=true CLIENT=saucelabs:safari:10 COMMAND=test
    # xvfb started failing, removing it broke chrome tests
    # https://github.com/pouchdb/pouchdb/issues/7625
    - env: CLIENT=selenium:chrome CHROME_BIN=/usr/bin/chromium-browser COMMAND=test
    - env: TYPE=mapreduce CLIENT=selenium:chrome CHROME_BIN=/usr/bin/chromium-browser COMMAND=test
    - env: TYPE=find PLUGINS=pouchdb-find CLIENT=selenium:chrome CHROME_BIN=/usr/bin/chromium-browser SERVER=pouchdb-server COMMAND=test


branches:
  only:
  - master
  - /^greenkeeper/.*$/

cache:
  directories:
  - $HOME/.npm
  # See https://github.com/gr2m/selsa
  - node_modules/selenium-standalone/.selenium
